packages:
  - packages/*
  # exclude discord-scrapper
  - '!packages/discord-scrapper'

catalogs:
  # Default catalog for common dependencies
  default:
    # React ecosystem
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^18.2.0
    "@types/react-dom": ^18.2.0
    next: ^15.2.1
    eslint-config-next: ^15.2.1
    
    # Auth
    "@auth/core": ^0.37.2
    "@auth/drizzle-adapter": ^1.7.4
    next-auth: ^5.0.0-beta.25
    
    # Development tools
    typescript: ^5.0.0
    eslint: ^8.0.0
    prettier: ^3.0.0
    tailwindcss: ^3.3.0
    postcss: ^8.0.0
    autoprefixer: ^10.4.20
    
    # Tanstack & tRPC
    "@tanstack/react-query": ^5.67.1
    "@trpc/client": ^11.0.0-rc.824
    "@trpc/server": ^11.0.0-rc.824
    "@trpc/tanstack-react-query": ^11.0.0-rc.824
    
    # Misc
    zod: ^3.24.1

  # Request Network dependencies
  request:
    "@requestnetwork/epk-cipher": ^0.9.0
    "@requestnetwork/epk-signature": ^0.9.9
    "@requestnetwork/payment-processor": ^0.56.0
    "@requestnetwork/request-client.js": ^0.58.0
    "@requestnetwork/types": ^0.53.0
    "@requestnetwork/utils": ^0.53.0
    "@requestnetwork/web3-signature": ^0.8.9